#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 103
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 72
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  sym_identifier = 1,
  anon_sym_LPAREN = 2,
  anon_sym_when = 3,
  anon_sym_RPAREN = 4,
  anon_sym_if = 5,
  anon_sym_each = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_for = 9,
  anon_sym_while = 10,
  anon_sym_let = 11,
  anon_sym_local = 12,
  anon_sym_var = 13,
  anon_sym_global = 14,
  anon_sym_fn = 15,
  anon_sym_lambda = 16,
  anon_sym_LBRACE = 17,
  anon_sym_RBRACE = 18,
  anon_sym_DQUOTE = 19,
  anon_sym_SQUOTE = 20,
  aux_sym_string_token1 = 21,
  sym_number = 22,
  anon_sym_PLUS = 23,
  anon_sym_DASH = 24,
  anon_sym_STAR = 25,
  anon_sym__ = 26,
  anon_sym_DOT_DOT = 27,
  anon_sym_DOT = 28,
  anon_sym_EQ = 29,
  anon_sym_PERCENT = 30,
  anon_sym_true = 31,
  anon_sym_false = 32,
  anon_sym_nil = 33,
  sym_comment = 34,
  sym_program = 35,
  sym__statement = 36,
  sym__function = 37,
  sym__variable_declaration = 38,
  sym__iterator = 39,
  sym__conditional = 40,
  sym_when_statement = 41,
  sym_if_statement = 42,
  sym_each = 43,
  sym_each_clause = 44,
  sym_for = 45,
  sym_for_clause = 46,
  sym_while = 47,
  sym_let_definition = 48,
  sym_local_definition = 49,
  sym_var_definition = 50,
  sym_global_definition = 51,
  sym_assignments = 52,
  sym_assignment = 53,
  sym_function_definition = 54,
  sym_lambda_definition = 55,
  sym__function_body = 56,
  sym_parameters = 57,
  sym_function_call = 58,
  sym_sequential_table = 59,
  sym_table = 60,
  sym__expression = 61,
  sym_string = 62,
  sym__operator = 63,
  sym_boolean = 64,
  sym_nil = 65,
  aux_sym_program_repeat1 = 66,
  aux_sym_when_statement_repeat1 = 67,
  aux_sym_assignments_repeat1 = 68,
  aux_sym_parameters_repeat1 = 69,
  aux_sym_table_repeat1 = 70,
  aux_sym_string_repeat1 = 71,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_when] = "when",
  [anon_sym_RPAREN] = ")",
  [anon_sym_if] = "if",
  [anon_sym_each] = "each",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_for] = "for",
  [anon_sym_while] = "while",
  [anon_sym_let] = "let",
  [anon_sym_local] = "local",
  [anon_sym_var] = "var",
  [anon_sym_global] = "global",
  [anon_sym_fn] = "fn",
  [anon_sym_lambda] = "lambda",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [sym_number] = "number",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_DOT] = ".",
  [anon_sym_EQ] = "=",
  [anon_sym_PERCENT] = "%",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_nil] = "nil",
  [sym_comment] = "comment",
  [sym_program] = "program",
  [sym__statement] = "_statement",
  [sym__function] = "_function",
  [sym__variable_declaration] = "_variable_declaration",
  [sym__iterator] = "_iterator",
  [sym__conditional] = "_conditional",
  [sym_when_statement] = "when_statement",
  [sym_if_statement] = "if_statement",
  [sym_each] = "each",
  [sym_each_clause] = "each_clause",
  [sym_for] = "for",
  [sym_for_clause] = "for_clause",
  [sym_while] = "while",
  [sym_let_definition] = "let_definition",
  [sym_local_definition] = "local_definition",
  [sym_var_definition] = "var_definition",
  [sym_global_definition] = "global_definition",
  [sym_assignments] = "assignments",
  [sym_assignment] = "assignment",
  [sym_function_definition] = "function_definition",
  [sym_lambda_definition] = "lambda_definition",
  [sym__function_body] = "_function_body",
  [sym_parameters] = "parameters",
  [sym_function_call] = "function_call",
  [sym_sequential_table] = "sequential_table",
  [sym_table] = "table",
  [sym__expression] = "_expression",
  [sym_string] = "string",
  [sym__operator] = "identifier",
  [sym_boolean] = "boolean",
  [sym_nil] = "nil",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_when_statement_repeat1] = "when_statement_repeat1",
  [aux_sym_assignments_repeat1] = "assignments_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_table_repeat1] = "table_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_when] = anon_sym_when,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_each] = anon_sym_each,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_global] = anon_sym_global,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_lambda] = anon_sym_lambda,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_number] = sym_number,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_nil] = anon_sym_nil,
  [sym_comment] = sym_comment,
  [sym_program] = sym_program,
  [sym__statement] = sym__statement,
  [sym__function] = sym__function,
  [sym__variable_declaration] = sym__variable_declaration,
  [sym__iterator] = sym__iterator,
  [sym__conditional] = sym__conditional,
  [sym_when_statement] = sym_when_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_each] = sym_each,
  [sym_each_clause] = sym_each_clause,
  [sym_for] = sym_for,
  [sym_for_clause] = sym_for_clause,
  [sym_while] = sym_while,
  [sym_let_definition] = sym_let_definition,
  [sym_local_definition] = sym_local_definition,
  [sym_var_definition] = sym_var_definition,
  [sym_global_definition] = sym_global_definition,
  [sym_assignments] = sym_assignments,
  [sym_assignment] = sym_assignment,
  [sym_function_definition] = sym_function_definition,
  [sym_lambda_definition] = sym_lambda_definition,
  [sym__function_body] = sym__function_body,
  [sym_parameters] = sym_parameters,
  [sym_function_call] = sym_function_call,
  [sym_sequential_table] = sym_sequential_table,
  [sym_table] = sym_table,
  [sym__expression] = sym__expression,
  [sym_string] = sym_string,
  [sym__operator] = sym_identifier,
  [sym_boolean] = sym_boolean,
  [sym_nil] = sym_nil,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_when_statement_repeat1] = aux_sym_when_statement_repeat1,
  [aux_sym_assignments_repeat1] = aux_sym_assignments_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_table_repeat1] = aux_sym_table_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_when] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_each] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_global] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lambda] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nil] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__function] = {
    .visible = false,
    .named = true,
  },
  [sym__variable_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym__iterator] = {
    .visible = false,
    .named = true,
  },
  [sym__conditional] = {
    .visible = false,
    .named = true,
  },
  [sym_when_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_each] = {
    .visible = true,
    .named = true,
  },
  [sym_each_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_for] = {
    .visible = true,
    .named = true,
  },
  [sym_for_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_while] = {
    .visible = true,
    .named = true,
  },
  [sym_let_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_local_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_var_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_global_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_assignments] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__function_body] = {
    .visible = false,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_sequential_table] = {
    .visible = true,
    .named = true,
  },
  [sym_table] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__operator] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_when_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_assignments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_condition = 2,
  field_name = 3,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_condition] = "condition",
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[7] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_condition, 2},
  [2] =
    {field_name, 0},
  [3] =
    {field_body, 2, .inherited = true},
    {field_name, 2, .inherited = true},
  [5] =
    {field_body, 1},
  [6] =
    {field_body, 2},
    {field_name, 0},
};

static TSSymbol ts_alias_sequences[7][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == '%') ADVANCE(23);
      if (lookahead == '\'') ADVANCE(11);
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == ')') ADVANCE(5);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(16);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == ';') ADVANCE(25);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '[') ADVANCE(6);
      if (lookahead == ']') ADVANCE(7);
      if (lookahead == '_') ADVANCE(19);
      if (lookahead == '{') ADVANCE(8);
      if (lookahead == '}') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (lookahead == ':' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == '\'') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == '\'') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(20);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'g') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (lookahead == 'v') ADVANCE(8);
      if (lookahead == 'w') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(12);
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'h') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 16:
      if (lookahead == 'm') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(33);
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'h') ADVANCE(35);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(36);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 26:
      if (lookahead == 'b') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 'b') ADVANCE(38);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_nil);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_each);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 38:
      if (lookahead == 'd') ADVANCE(45);
      END_STATE();
    case 39:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_when);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 44:
      if (lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 45:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_global);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_lambda);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_when] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_each] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_global] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_lambda] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_nil] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(98),
    [sym__statement] = STATE(2),
    [sym__function] = STATE(2),
    [sym__variable_declaration] = STATE(2),
    [sym__iterator] = STATE(2),
    [sym__conditional] = STATE(2),
    [sym_when_statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_each] = STATE(2),
    [sym_for] = STATE(2),
    [sym_while] = STATE(2),
    [sym_let_definition] = STATE(2),
    [sym_local_definition] = STATE(2),
    [sym_var_definition] = STATE(2),
    [sym_global_definition] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym_lambda_definition] = STATE(2),
    [sym_function_call] = STATE(2),
    [sym_sequential_table] = STATE(2),
    [sym_table] = STATE(2),
    [sym__expression] = STATE(2),
    [sym_string] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym_nil] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_nil] = ACTIONS(19),
    [sym_comment] = ACTIONS(15),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_number,
      sym_comment,
    STATE(3), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_program_repeat1,
  [57] = 10,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      anon_sym_nil,
    ACTIONS(41), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(44), 2,
      sym_number,
      sym_comment,
    ACTIONS(47), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_program_repeat1,
  [114] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(53), 1,
      sym_identifier,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [170] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(53), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(59), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [226] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(53), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(61), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [282] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(53), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(63), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [338] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    ACTIONS(69), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [394] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_RPAREN,
    ACTIONS(75), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(13), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [450] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
    ACTIONS(81), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(6), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [506] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(83), 1,
      sym_identifier,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(87), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [562] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(53), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(89), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [618] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(53), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [674] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(53), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [730] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    ACTIONS(99), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(14), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [786] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    ACTIONS(105), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [842] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(53), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [898] = 10,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(112), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    ACTIONS(117), 1,
      anon_sym_LBRACK,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
    ACTIONS(126), 1,
      sym_number,
    ACTIONS(132), 1,
      anon_sym_nil,
    ACTIONS(123), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(129), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [954] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    ACTIONS(139), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [1010] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(53), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [1066] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    ACTIONS(147), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [1122] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(149), 1,
      sym_identifier,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
    ACTIONS(153), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 24,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_when_statement_repeat1,
  [1178] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(157), 1,
      anon_sym_RBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(101), 23,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
  [1233] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(163), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(83), 23,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
  [1285] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(167), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(23), 23,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
  [1337] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(171), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 23,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
  [1389] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(175), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(82), 23,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
  [1441] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(179), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 23,
      sym__statement,
      sym__function,
      sym__variable_declaration,
      sym__iterator,
      sym__conditional,
      sym_when_statement,
      sym_if_statement,
      sym_each,
      sym_for,
      sym_while,
      sym_let_definition,
      sym_local_definition,
      sym_var_definition,
      sym_global_definition,
      sym_function_definition,
      sym_lambda_definition,
      sym_function_call,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
  [1493] = 15,
    ACTIONS(181), 1,
      sym_identifier,
    ACTIONS(183), 1,
      anon_sym_when,
    ACTIONS(185), 1,
      anon_sym_if,
    ACTIONS(187), 1,
      anon_sym_each,
    ACTIONS(189), 1,
      anon_sym_for,
    ACTIONS(191), 1,
      anon_sym_while,
    ACTIONS(193), 1,
      anon_sym_let,
    ACTIONS(195), 1,
      anon_sym_local,
    ACTIONS(197), 1,
      anon_sym_var,
    ACTIONS(199), 1,
      anon_sym_global,
    ACTIONS(201), 1,
      anon_sym_fn,
    ACTIONS(203), 1,
      anon_sym_lambda,
    ACTIONS(207), 1,
      anon_sym_DOT,
    STATE(21), 1,
      sym__operator,
    ACTIONS(205), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_DOT_DOT,
      anon_sym_EQ,
      anon_sym_PERCENT,
  [1545] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(209), 1,
      sym_identifier,
    ACTIONS(211), 1,
      anon_sym_RBRACK,
    ACTIONS(213), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(31), 7,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_parameters_repeat1,
  [1581] = 9,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(218), 1,
      anon_sym_LBRACK,
    ACTIONS(221), 1,
      anon_sym_RBRACK,
    ACTIONS(223), 1,
      anon_sym_LBRACE,
    ACTIONS(229), 1,
      sym_number,
    ACTIONS(235), 1,
      anon_sym_nil,
    ACTIONS(226), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(232), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(31), 7,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_parameters_repeat1,
  [1617] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(238), 1,
      sym_identifier,
    ACTIONS(240), 1,
      anon_sym_RBRACK,
    ACTIONS(242), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 7,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_parameters_repeat1,
  [1653] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(244), 1,
      sym_identifier,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
    ACTIONS(248), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 7,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_parameters_repeat1,
  [1689] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_nil,
    ACTIONS(209), 1,
      sym_identifier,
    ACTIONS(213), 1,
      sym_number,
    ACTIONS(250), 1,
      anon_sym_RBRACK,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(31), 7,
      sym_sequential_table,
      sym_table,
      sym__expression,
      sym_string,
      sym_boolean,
      sym_nil,
      aux_sym_parameters_repeat1,
  [1725] = 2,
    ACTIONS(254), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(252), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1745] = 2,
    ACTIONS(258), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(256), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1765] = 2,
    ACTIONS(262), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(260), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1785] = 2,
    ACTIONS(266), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(264), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1805] = 2,
    ACTIONS(270), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(268), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1825] = 2,
    ACTIONS(274), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(272), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1845] = 2,
    ACTIONS(278), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(276), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1865] = 2,
    ACTIONS(282), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(280), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1885] = 2,
    ACTIONS(286), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(284), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1905] = 2,
    ACTIONS(290), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(288), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1925] = 2,
    ACTIONS(294), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(292), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1945] = 2,
    ACTIONS(298), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(296), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1965] = 2,
    ACTIONS(302), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(300), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [1985] = 2,
    ACTIONS(306), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(304), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2005] = 2,
    ACTIONS(310), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(308), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2025] = 2,
    ACTIONS(314), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(312), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2045] = 2,
    ACTIONS(318), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(316), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2065] = 2,
    ACTIONS(322), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(320), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2085] = 2,
    ACTIONS(326), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(324), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2105] = 2,
    ACTIONS(330), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(328), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2125] = 2,
    ACTIONS(334), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(332), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2145] = 2,
    ACTIONS(338), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(336), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2165] = 2,
    ACTIONS(342), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(340), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2185] = 2,
    ACTIONS(346), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(344), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2205] = 2,
    ACTIONS(350), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(348), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2225] = 2,
    ACTIONS(354), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(352), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2245] = 2,
    ACTIONS(358), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(356), 11,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_comment,
  [2265] = 2,
    ACTIONS(360), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(362), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
  [2281] = 2,
    ACTIONS(364), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(366), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
  [2297] = 2,
    ACTIONS(368), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(370), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
  [2313] = 2,
    ACTIONS(372), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(374), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
  [2329] = 2,
    ACTIONS(376), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(378), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
  [2345] = 2,
    ACTIONS(380), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(382), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
  [2361] = 2,
    ACTIONS(384), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(386), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
  [2377] = 2,
    ACTIONS(388), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_identifier,
    ACTIONS(390), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
  [2393] = 4,
    ACTIONS(207), 1,
      anon_sym_DOT,
    ACTIONS(392), 1,
      sym_identifier,
    STATE(21), 1,
      sym__operator,
    ACTIONS(205), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_DOT_DOT,
      anon_sym_EQ,
      anon_sym_PERCENT,
  [2412] = 4,
    ACTIONS(394), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      sym_string,
    STATE(73), 1,
      aux_sym_table_repeat1,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [2426] = 4,
    ACTIONS(396), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      sym_string,
    STATE(72), 1,
      aux_sym_table_repeat1,
    ACTIONS(398), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [2440] = 4,
    ACTIONS(401), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      sym_string,
    STATE(72), 1,
      aux_sym_table_repeat1,
    ACTIONS(13), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [2454] = 3,
    ACTIONS(403), 1,
      sym_identifier,
    ACTIONS(406), 1,
      anon_sym_RBRACK,
    STATE(74), 2,
      sym_assignment,
      aux_sym_assignments_repeat1,
  [2465] = 3,
    ACTIONS(408), 1,
      sym_identifier,
    ACTIONS(410), 1,
      anon_sym_RBRACK,
    STATE(79), 2,
      sym_assignment,
      aux_sym_assignments_repeat1,
  [2476] = 3,
    ACTIONS(414), 1,
      aux_sym_string_token1,
    STATE(76), 1,
      aux_sym_string_repeat1,
    ACTIONS(412), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [2487] = 4,
    ACTIONS(417), 1,
      sym_identifier,
    ACTIONS(419), 1,
      anon_sym_LBRACK,
    STATE(19), 1,
      sym_parameters,
    STATE(100), 1,
      sym__function_body,
  [2500] = 3,
    ACTIONS(423), 1,
      aux_sym_string_token1,
    STATE(80), 1,
      aux_sym_string_repeat1,
    ACTIONS(421), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [2511] = 3,
    ACTIONS(408), 1,
      sym_identifier,
    ACTIONS(425), 1,
      anon_sym_RBRACK,
    STATE(74), 2,
      sym_assignment,
      aux_sym_assignments_repeat1,
  [2522] = 3,
    ACTIONS(429), 1,
      aux_sym_string_token1,
    STATE(76), 1,
      aux_sym_string_repeat1,
    ACTIONS(427), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [2533] = 4,
    ACTIONS(417), 1,
      sym_identifier,
    ACTIONS(419), 1,
      anon_sym_LBRACK,
    STATE(19), 1,
      sym_parameters,
    STATE(102), 1,
      sym__function_body,
  [2546] = 1,
    ACTIONS(431), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      sym_identifier,
  [2552] = 1,
    ACTIONS(396), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [2558] = 2,
    ACTIONS(408), 1,
      sym_identifier,
    STATE(93), 1,
      sym_assignment,
  [2565] = 2,
    ACTIONS(433), 1,
      anon_sym_LPAREN,
    STATE(99), 1,
      sym_function_call,
  [2572] = 2,
    ACTIONS(435), 1,
      anon_sym_LBRACK,
    STATE(11), 1,
      sym_assignments,
  [2579] = 2,
    ACTIONS(408), 1,
      sym_identifier,
    STATE(94), 1,
      sym_assignment,
  [2586] = 2,
    ACTIONS(419), 1,
      anon_sym_LBRACK,
    STATE(8), 1,
      sym_parameters,
  [2593] = 2,
    ACTIONS(437), 1,
      anon_sym_LBRACK,
    STATE(22), 1,
      sym_each_clause,
  [2600] = 2,
    ACTIONS(439), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_for_clause,
  [2607] = 2,
    ACTIONS(408), 1,
      sym_identifier,
    STATE(92), 1,
      sym_assignment,
  [2614] = 1,
    ACTIONS(441), 1,
      anon_sym_RPAREN,
  [2618] = 1,
    ACTIONS(443), 1,
      anon_sym_RPAREN,
  [2622] = 1,
    ACTIONS(445), 1,
      anon_sym_RPAREN,
  [2626] = 1,
    ACTIONS(447), 1,
      sym_identifier,
  [2630] = 1,
    ACTIONS(449), 1,
      sym_identifier,
  [2634] = 1,
    ACTIONS(451), 1,
      sym_identifier,
  [2638] = 1,
    ACTIONS(453), 1,
      ts_builtin_sym_end,
  [2642] = 1,
    ACTIONS(455), 1,
      anon_sym_RBRACK,
  [2646] = 1,
    ACTIONS(457), 1,
      anon_sym_RPAREN,
  [2650] = 1,
    ACTIONS(459), 1,
      anon_sym_RBRACK,
  [2654] = 1,
    ACTIONS(461), 1,
      anon_sym_RPAREN,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 57,
  [SMALL_STATE(4)] = 114,
  [SMALL_STATE(5)] = 170,
  [SMALL_STATE(6)] = 226,
  [SMALL_STATE(7)] = 282,
  [SMALL_STATE(8)] = 338,
  [SMALL_STATE(9)] = 394,
  [SMALL_STATE(10)] = 450,
  [SMALL_STATE(11)] = 506,
  [SMALL_STATE(12)] = 562,
  [SMALL_STATE(13)] = 618,
  [SMALL_STATE(14)] = 674,
  [SMALL_STATE(15)] = 730,
  [SMALL_STATE(16)] = 786,
  [SMALL_STATE(17)] = 842,
  [SMALL_STATE(18)] = 898,
  [SMALL_STATE(19)] = 954,
  [SMALL_STATE(20)] = 1010,
  [SMALL_STATE(21)] = 1066,
  [SMALL_STATE(22)] = 1122,
  [SMALL_STATE(23)] = 1178,
  [SMALL_STATE(24)] = 1233,
  [SMALL_STATE(25)] = 1285,
  [SMALL_STATE(26)] = 1337,
  [SMALL_STATE(27)] = 1389,
  [SMALL_STATE(28)] = 1441,
  [SMALL_STATE(29)] = 1493,
  [SMALL_STATE(30)] = 1545,
  [SMALL_STATE(31)] = 1581,
  [SMALL_STATE(32)] = 1617,
  [SMALL_STATE(33)] = 1653,
  [SMALL_STATE(34)] = 1689,
  [SMALL_STATE(35)] = 1725,
  [SMALL_STATE(36)] = 1745,
  [SMALL_STATE(37)] = 1765,
  [SMALL_STATE(38)] = 1785,
  [SMALL_STATE(39)] = 1805,
  [SMALL_STATE(40)] = 1825,
  [SMALL_STATE(41)] = 1845,
  [SMALL_STATE(42)] = 1865,
  [SMALL_STATE(43)] = 1885,
  [SMALL_STATE(44)] = 1905,
  [SMALL_STATE(45)] = 1925,
  [SMALL_STATE(46)] = 1945,
  [SMALL_STATE(47)] = 1965,
  [SMALL_STATE(48)] = 1985,
  [SMALL_STATE(49)] = 2005,
  [SMALL_STATE(50)] = 2025,
  [SMALL_STATE(51)] = 2045,
  [SMALL_STATE(52)] = 2065,
  [SMALL_STATE(53)] = 2085,
  [SMALL_STATE(54)] = 2105,
  [SMALL_STATE(55)] = 2125,
  [SMALL_STATE(56)] = 2145,
  [SMALL_STATE(57)] = 2165,
  [SMALL_STATE(58)] = 2185,
  [SMALL_STATE(59)] = 2205,
  [SMALL_STATE(60)] = 2225,
  [SMALL_STATE(61)] = 2245,
  [SMALL_STATE(62)] = 2265,
  [SMALL_STATE(63)] = 2281,
  [SMALL_STATE(64)] = 2297,
  [SMALL_STATE(65)] = 2313,
  [SMALL_STATE(66)] = 2329,
  [SMALL_STATE(67)] = 2345,
  [SMALL_STATE(68)] = 2361,
  [SMALL_STATE(69)] = 2377,
  [SMALL_STATE(70)] = 2393,
  [SMALL_STATE(71)] = 2412,
  [SMALL_STATE(72)] = 2426,
  [SMALL_STATE(73)] = 2440,
  [SMALL_STATE(74)] = 2454,
  [SMALL_STATE(75)] = 2465,
  [SMALL_STATE(76)] = 2476,
  [SMALL_STATE(77)] = 2487,
  [SMALL_STATE(78)] = 2500,
  [SMALL_STATE(79)] = 2511,
  [SMALL_STATE(80)] = 2522,
  [SMALL_STATE(81)] = 2533,
  [SMALL_STATE(82)] = 2546,
  [SMALL_STATE(83)] = 2552,
  [SMALL_STATE(84)] = 2558,
  [SMALL_STATE(85)] = 2565,
  [SMALL_STATE(86)] = 2572,
  [SMALL_STATE(87)] = 2579,
  [SMALL_STATE(88)] = 2586,
  [SMALL_STATE(89)] = 2593,
  [SMALL_STATE(90)] = 2600,
  [SMALL_STATE(91)] = 2607,
  [SMALL_STATE(92)] = 2614,
  [SMALL_STATE(93)] = 2618,
  [SMALL_STATE(94)] = 2622,
  [SMALL_STATE(95)] = 2626,
  [SMALL_STATE(96)] = 2630,
  [SMALL_STATE(97)] = 2634,
  [SMALL_STATE(98)] = 2638,
  [SMALL_STATE(99)] = 2642,
  [SMALL_STATE(100)] = 2646,
  [SMALL_STATE(101)] = 2650,
  [SMALL_STATE(102)] = 2654,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(3),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(29),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(32),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(71),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(78),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(3),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(37),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(44),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_body, 3, .production_id = 6),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_body, 2, .production_id = 5),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_body, 2, .production_id = 3),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_when_statement_repeat1, 2), SHIFT_REPEAT(18),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_when_statement_repeat1, 2), SHIFT_REPEAT(29),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_when_statement_repeat1, 2),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_when_statement_repeat1, 2), SHIFT_REPEAT(32),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_when_statement_repeat1, 2), SHIFT_REPEAT(71),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_when_statement_repeat1, 2), SHIFT_REPEAT(78),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_when_statement_repeat1, 2), SHIFT_REPEAT(18),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_when_statement_repeat1, 2), SHIFT_REPEAT(37),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_when_statement_repeat1, 2), SHIFT_REPEAT(44),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_body, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(31),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(32),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(71),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(78),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(31),
  [232] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(37),
  [235] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(44),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, .production_id = 1),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, .production_id = 1),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while, 4, .production_id = 2),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while, 4, .production_id = 2),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_definition, 5),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_definition, 5),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_when_statement, 3),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_when_statement, 3),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while, 5, .production_id = 2),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while, 5, .production_id = 2),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for, 5),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for, 5),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nil, 1),
  [290] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nil, 1),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each, 5),
  [294] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each, 5),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, .production_id = 1),
  [298] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, .production_id = 1),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda_definition, 4, .production_id = 4),
  [302] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lambda_definition, 4, .production_id = 4),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, .production_id = 4),
  [306] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4, .production_id = 4),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global_definition, 4),
  [310] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_global_definition, 4),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_definition, 4),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_definition, 4),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_definition, 4),
  [318] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_local_definition, 4),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequential_table, 2),
  [322] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequential_table, 2),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequential_table, 3),
  [326] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequential_table, 3),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_definition, 4),
  [330] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_definition, 4),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 2),
  [334] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table, 2),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 3),
  [338] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table, 3),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for, 4),
  [342] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for, 4),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [346] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [348] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each, 4),
  [350] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each, 4),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_when_statement, 4),
  [354] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_when_statement, 4),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4),
  [358] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 4),
  [360] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_clause, 6),
  [362] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_clause, 6),
  [364] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_clause, 5),
  [366] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_clause, 5),
  [368] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_clause, 5),
  [370] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_clause, 5),
  [372] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameters, 3),
  [374] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3),
  [376] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignments, 3),
  [378] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignments, 3),
  [380] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignments, 2),
  [382] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignments, 2),
  [384] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameters, 2),
  [386] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
  [388] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__operator, 1),
  [390] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__operator, 1),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [396] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2),
  [398] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2), SHIFT_REPEAT(78),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [403] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assignments_repeat1, 2), SHIFT_REPEAT(27),
  [406] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_assignments_repeat1, 2),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [412] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [414] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(76),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [421] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [423] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [427] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [429] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [431] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 2),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [435] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [437] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [439] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [441] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [443] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [445] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [447] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [449] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [451] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [453] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [455] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [457] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [459] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [461] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_fennel(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
